filebeat.idemots:
- type: container
  paths: 
    - '/mnt/docker/containers/*/*.log'

processors:
- add_docker_metadata:
    host: "unix:///var/run/docker.sock"

- decode_json_fields:
    fields: ["message"]
    target: "json"
    overwrite_keys: true

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  username: "elastic" 
  password: "labterm2"
  indices:
    - index: "filebeat-elastic-%{+yyyy.MM.dd}"
      when.or:
        - equals:
            container.image.name: docker.elastic.co/elasticsearch/elasticsearch:7.14.2
        - equals:
            container.image.name: docker.elastic.co/kibana/kibana:7.14.2
        - equals:
            container.image.name: docker.elastic.co/beats/filebeat:7.14.2
    - index: "filebeat-dev-%{+yyyy.MM.dd}"
  
logging.json: true
logging.metrics.enabled: false
