* Guideline - Nyt modul xyz
10. Opret en folder her src/main/java/cgi/labterm/services/npu/entities/xyz
20. Opret en Xyz-klasse i ovenstående folder og tilret f.x. med brug af Jpa-buddy.
30. Xyz-klasse skal extende Kontekst (efterlign Organisation.java)
40. Højre-klik på Xyz-klassen og eksporter DDL
50. Tilføj DDL-fil i src/main/resources/db/migration, vælg en ny 100-serie
60. Åbn generatorNpu-projektet og opret en xyz.xml fil i ~/npu/generatorNpu/definitions/. Husk at angive ifnavn attribut for ManyToOne entiteter og enumns
70. Generer og kopier output til en editor
80. Opret en ny klasse XyzModel i src/main/java/cgi/labterm/lib/gateway/model og tilføj fra generatoroutput
90. Opret et nyt interface XyzInterface i src/main/java/cgi/labterm/services/npu/entities/xyz og tilføj fra generatoroutput - ToDo skal ikke have status med
100. Opret en ny klasse, XyzDTO, i src/main/java/cgi/labterm/services/npu/dto og tilføj fra generatoroutput - der skal håndrettes noget
110. Lad Xyz.java implementere XyzInterface - tilføj manglende metoder
120. Kopier Xyz-klasse til XyzDraft-klasse i ../entities/xyz og tilret @Table og tilret id-felt så den bruger den rigtige sekvens
130. I XyzDraft fjern annoteringer på columns som nullable, default mm.
140. I XyzDraft erstattes Many-relationer og enums med simple String. Generer friske getter og setter og tilføj manglende metoder for at implementere XyzInterface
150. Kopier XyzDraft til XyzRevision og lav søg-og-erstat draft med revision. Tilføj trigger og functiondel fra genereret output.
160. Tilret id-kolonnen (se OrganisationRevision) og fjern get/set til id og lav get/set til ny id-kolonne
170. Tilføj @IdClass(XyzRevisionId.class) attribute
180. Implementer interface (getUpdatedAt og getId)
190. Kopier src/main/java/cgi/labterm/services/npu/entities/organisation/OrganisationRevisionId.java til ../entities/xyz/XyzRevisionID.java og tilret organisationId-attribut
200. Kopier ../entities/xyz/XyzRevision.java til XyzView.java
210. Tilret XyzView:  @Table, extends Kontekts, simpel id-felt, sæt @immutable attribut
220. Fjern get/set og lav kun getter
230. Kopier DDL-filen i til src/main/resources/db/migration/Vx40__xyz_draft.sql. Tilret tabelnavn og pk-constraint. Fjern øvrige constraints
240. Kopier src/main/resources/db/migration/V50__organisation_view.sql til src/main/resources/db/migration/Vx50__xyz_view.sql. søg-og-erstat organisation med xyz. Rediger attributterne efter optlock
250. Sikkert et godt tidspunkt at afvikle test for at se at tabeller kan oprettes og det hele compilerer
260. Optionelt - tilføj eksempelattributter i migration insert statements
270. Lav en ny xyz volume under src/main/java/cgi/labterm/services/npu/repositories og kopier repositoryklasser fra ../repositories/organisation
280. Lav søg og erstat i det volume på organisation med xyz (bevar case) . Og omdøb de enkelte filer fra organisation til xyz. (og evt. fjern metoder)
290. Kopier src/main/java/cgi/labterm/services/npu/service/OrganisationService.java til ../XyzService.java og lav søg-og-erstat i filen med organisation til xyz (bevar case)
300. Så det bare at tilrette den nye serviceklasse
310. Kopier src/main/java/cgi/labterm/services/npu/controller/OrganisationController.java til ../XyzController.java og lav søg-og-erstat i filen med organisation til xyz (bevar case)
320. Tilret controllerklasse
33. 
    
   
