version: '3'

networks:
  default:
    external:
      name: npu-network

services:

  postgres:
    image: "postgres:14.0-alpine"
    container_name: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=demo
      - POSTGRES_USER=demo
      - POSTGRES_DB=demo
    volumes:
      - ./postgres-data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    expose:
      - 5432

  jaeger:
    image: jaegertracing/all-in-one:1.25
    container_name: jaeger
    restart: unless-stopped
    ports:
      - 6831:6831/udp
      - 6832:6832/udp
      - 16686:16686
      - 14268:14268
    expose:
      - 16686

  keycloak:
    image: jboss/keycloak
    container_name: keycloak
    environment:
      - KEYCLOAK_PASSWORD=keycloak
      - KEYCLOAK_USER=keycloak
      - DB_DATABASE=demo
      - DB_USER=keycloak
      - DB_PASSWORD=keycloak
      - DB_SCHEMA=keycloak
      - DB_ADDR=localhost,postgres
    ports:
      - 8080:8080
    expose:
      - 8080
