CREATE TABLE elementbegreb
(
    id                                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    status                                  VARCHAR(255)                            NOT NULL,
    virkning_fra                            DATE                     DEFAULT CURRENT_DATE,
    created_at                              TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at                              TIMESTAMP WITH TIME ZONE,
    brugernavn                              VARCHAR(255)                            NOT NULL,
    optlock                                 INTEGER,
    element_kode                            VARCHAR(255)                            NOT NULL,
    releasecenter_kort_navn                 VARCHAR(255),
    elementbegreb_erstatter_element_kode    VARCHAR(255),
    elementbegreb_erstattet_af_element_kode VARCHAR(255),
    definerende_id_hos_org                  VARCHAR(255),
    definerende_tekst                       VARCHAR(255),
    organisation_kort_navn                  VARCHAR(255),
    elementterm_id                          BIGINT,
    term_lang                               VARCHAR(255)                            ,
    term_kort                               VARCHAR(255)                            ,
    internalhandle                          VARCHAR(255),
    active_at                               TIMESTAMP WITH TIME ZONE,
    elementbegreb_note_id                   BIGINT,
    CONSTRAINT pk_elementbegreb PRIMARY KEY (id)
);

ALTER TABLE elementbegreb
    ADD CONSTRAINT uc_elementbegreb_element_kode UNIQUE (element_kode);

ALTER TABLE elementbegreb
    ADD CONSTRAINT FK_ELEMENTBEGREB_ON_ELEMENTBEGREB_ERSTATTER_ELEMENT_KODE FOREIGN KEY (elementbegreb_erstatter_element_kode) REFERENCES elementbegreb (element_kode);

ALTER TABLE elementbegreb
    ADD CONSTRAINT FK_ELEMENTBEGREB_ON_ELEMENTBEGREB_ERSTATTET_AF_ELEMENT_KODE FOREIGN KEY (elementbegreb_erstattet_af_element_kode) REFERENCES elementbegreb (element_kode);

ALTER TABLE elementbegreb
    ADD CONSTRAINT FK_ELEMENTBEGREB_ON_RELEASECENTER_KORT_NAVN FOREIGN KEY (releasecenter_kort_navn) REFERENCES organisation (kort_navn);

ALTER TABLE elementbegreb
    ADD CONSTRAINT FK_ELEMENTBEGREB_ON_ORGANISATION_KORT_NAVN FOREIGN KEY (organisation_kort_navn) REFERENCES organisation (kort_navn);


CREATE TABLE elementbegreb_note
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tekst                  TEXT                                    NOT NULL,
    bruger                 VARCHAR(255)                            NOT NULL,
    created_at             TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at             TIMESTAMP WITH TIME ZONE,
    optlock                INTEGER                                 NOT NULL,
    elementbegreb_id       BIGINT,
    elementbegreb_draft_id BIGINT,
    CONSTRAINT pk_elementbegreb_note PRIMARY KEY (id)
);

ALTER TABLE elementbegreb
    ADD CONSTRAINT FK_ELEMENTBEGREB_ON_ELEMENTBEGREB_NOTE FOREIGN KEY (elementbegreb_note_id) REFERENCES elementbegreb_note (id);
